use std::fmt::{self, Display};

#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum Instructions {
    Arithmetic,
    Assertion,
    Assignment,
    Automaton,
    Base64,
    Base64Var,
    Biguint,
    Binary,
    Bitwise,
    Canonicity,
    CommittedInstance,
    Comparison,
    ControlFlow,
    Conversion,
    CoreDecomposition,
    Decomposition,
    Division,
    Ecc,
    Equality,
    Field,
    ForeignEcc,
    Hash,
    HashToCurve,
    Map,
    MapToCurve,
    Parser,
    Pow2Range,
    PublicInput,
    RangeCheck,
    Sha256,
    Sponge,
    Stdlib,
    UnsafeConversion,
    Varhash,
    Vector,
    Zero,
}

impl Display for Instructions {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Instructions::Arithmetic => "arithmetic",
                Instructions::Assertion => "assertion",
                Instructions::Assignment => "assignment",
                Instructions::Automaton => "automaton",
                Instructions::Base64 => "base64",
                Instructions::Base64Var => "base64var",
                Instructions::Biguint => "biguint",
                Instructions::Binary => "binary",
                Instructions::Bitwise => "bitwise",
                Instructions::Canonicity => "canonicity",
                Instructions::CommittedInstance => "committed-instance",
                Instructions::Comparison => "comparison",
                Instructions::ControlFlow => "control-flow",
                Instructions::Conversion => "conversion",
                Instructions::CoreDecomposition => "core-decomposition",
                Instructions::Decomposition => "decomposition",
                Instructions::Division => "division",
                Instructions::Ecc => "ecc",
                Instructions::Equality => "equality",
                Instructions::Field => "field",
                Instructions::ForeignEcc => "foreign-ecc",
                Instructions::Hash => "hash",
                Instructions::HashToCurve => "hash-to-curve",
                Instructions::Map => "map",
                Instructions::MapToCurve => "map-to-curve",
                Instructions::Parser => "parser",
                Instructions::Pow2Range => "pow2range",
                Instructions::PublicInput => "public-input",
                Instructions::RangeCheck => "range-check",
                Instructions::Sha256 => "sha256",
                Instructions::Sponge => "sponge",
                Instructions::Stdlib => "stdlib",
                Instructions::UnsafeConversion => "unsafe-conversion",
                Instructions::Varhash => "varhash",
                Instructions::Vector => "vector",
                Instructions::Zero => "zero",
            }
        )
    }
}
